version: '3.8'

services:
  jadwala-app:
    build:
      context: .
      args:
        # تأكد أن الأسماء هنا تطابق تماماً الأسماء في ملف .env
        VITE_SUPABASE_URL="https://lhilcaymbhticyafyimb.supabase.co"
        VITE_SUPABASE_PUBLISHABLE_KEY="eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImxoaWxjYXltYmh0aWN5YWZ5aW1iIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzAzNTI4NTEsImV4cCI6MjA4NTkyODg1MX0.8RJxjC0kSbROkmcgNPzPJVR9Qv9XFolqVCbJz2ICnLQ"

    ports:
      - "8080:80"
    env_file:
      - .env